<?php

	/**
	 * Created by PhpStorm.
	 * User: jameswillhoitejr.
	 * Date: 9/9/18
	 * Time: 3:53 PM
	 */
	require_once "controller.php";

	class projectJS extends controller
	{
		private $return;
		public function __construct()
		{
			$this->return = new ArrayObject(array('error' => false, 'error_msg' => '', 'data' => null), 2);
			parent::__construct();
		}


		public function getStyles() {

			$model = $this->getModel("Project");
			$result = $model->getStyles();

			if($result['error']) {
				$this->return->error = true;
				$this->return->error_msg = $result['error_msg'];
				$this->debug("Error: " . $result['error_msg']);
				echo json_encode($this->return);
				exit();
			}

			$this->return->data = $result['data'];
			echo json_encode($this->return);
			exit();
		}

		/**
		 * @param string $name
		 * @param string $prefix
		 *
		 * @return ProjectModelProject
		 */
		public function &getModel($name = 'Project', $prefix = "ProjectModel")
		{
			$model = parent::getModel($name, $prefix); // TODO: Change the autogenerated stub
			return $model;
		}

		public function getCustomerList() {
			$model = $this->getModel();

			$name = $this->input->getString("name");

			if(!$name) {
				$this->return->error = true;
				$this->return->error_msg = "No Name Given";
				echo json_encode($this->return);
				exit();
			}

			$result = $model->getCustomerList($name);
			if($result->error) {
				$this->return->error = true;
				$this->return->error_msg = $result->error_msg;
				echo json_encode($this->return);
				exit();
			}
			$this->return->data = $result->data;
			echo json_encode($this->return);
			exit();
		}

		public function getAddressList() {
			$address = $this->input->getString("address");

			if(!$address) {
				$this->return->error = true;
				$this->return->error_msg = "No address Given";
				echo json_encode($this->return);
				exit();
			}

			$model = $this->getModel();
			$result = $model->getAddressList($address);
			if($result->error) {
				$this->return->error = true;
				$this->return->error_msg = $result->error_msg;
				echo json_encode($this->return);
				exit();
			}

			$this->return->data = $result->data;
			echo json_encode($this->return);
			exit();

		}

		public function saveCustomer() {
			$customerID = $this->input->getInt('customerID');
			$addressID = $this->input->getInt('addressID');
			$jobID = $this->input->getInt('jobID');
			$dateSold = $this->input->getString('dateSold');

			if(!$customerID || !$addressID) {
				$this->return->error = true;
				$this->return->error_msg = "No Customer or Address Given";
				echo json_encode($this->return);
				exit();
			}

			$model = $this->getModel();

			if(!$jobID || $jobID == 0) {
				$result = $model->getJobNumber($customerID, $addressID);
				$jobID = $result->data;
			}
			else {
				$result = $model->updateHeaderCustomer($jobID, $customerID, $addressID);
			}

			if($result->error) {
				$this->return->error = true;
				$this->return->error_msg = $result->error_msg;
				echo json_encode($this->return);
				exit();
			}

			@$this->return->data->jobID = (int)$jobID;
			echo json_encode($this->return);
			exit();


		}

		public function addCustomer() {
			$model = $this->getModel();
			$customerName = $this->input->getString("customerName");
			$phoneType = $this->input->getString("phoneType");
			$phone = $this->input->getString("phone");
			$email = $this->input->getString("email");

			if(!$customerName) {
				echo $this->message("No Customer Name Given");
				exit();
			}
			elseif (!$phone) {
				echo $this->message("No Phone Number Given");
				exit();
			}

			$result = $model->addCustomer($customerName, $phoneType, $phone, $email);

			if($result->error) {
				echo $this->message($result->error_msg);
				exit();
			}

			//Return the new Customer ID
			$this->return->data = $result->data;
			echo json_encode($this->return);
			exit();


		}

		private function message($txt) {
			$this->return->error = true;
			$this->return->error_msg = $txt;
			return json_encode($this->return);
		}

	}